### ISSUE TITLE
Styling Fix on Comment Box

### ISSUE THREAD

**Issue by Archiehere** [ConnectPlus-Org/ConnectPlus-Frontend#13]
The comment section looks slightly abnormal. Requires a little stlying Fix.

![image](https://github.com/ConnectPlus-Org/ConnectPlus-Frontend/assets/66951703/92d6c117-25cf-4983-a2c1-32d0be79dbb6)

the Circle should preferably be behind the input component.

**Comment by Krish-Panchani** [comment]
Assign me, I can Fix it

**Comment by PrathameshTheurkar** [comment]
Can you assign this issue to me , I would love to contribute to this issue .

**Comment by Krish-Panchani** [comment]
![image](https://github.com/ConnectPlus-Org/ConnectPlus-Frontend/assets/74005086/7b281aad-daae-45b0-bacd-abcb09879f82)

you want this comment box avatar circule like this?

**Comment by Archiehere** [comment]
> ![image](https://github.com/ConnectPlus-Org/ConnectPlus-Frontend/assets/74005086/7b281aad-daae-45b0-bacd-abcb09879f82)
> 
> 
> 
> you want this comment box avatar circule like this?

Yeah, looks better than before. You can style the circle better by centering it in the input box and make sure it works on all screen sizes.
