### ISSUE TITLE
Styles fixing at forms and inputs

### ISSUE THREAD

**Issue by danyelica** [ConnectPlus-Org/ConnectPlus-Frontend#29]
- Add spacing at **Don't Have An Account?Sign Up** text;
![image](https://github.com/ConnectPlus-Org/ConnectPlus-Frontend/assets/75343999/f85c3be4-0f00-443b-8f10-2aea721932db)
- Add spacing at **Already Have An Account?Log In** text;
- Login/Register possible with Enter key;
- Add padding at this input 
![image](https://github.com/ConnectPlus-Org/ConnectPlus-Frontend/assets/75343999/8836571a-ad5e-4349-895b-eb105f5649fc)

Assign to me please!!

**Comment by Tech-Shreyansh** [comment]
> * Add spacing at **Don't Have An Account?Sign Up** text;
>   ![image](https://user-images.githubusercontent.com/75343999/273672725-f85c3be4-0f00-443b-8f10-2aea721932db.png)
> * Add spacing at **Already Have An Account?Log In** text;
> * Login/Register possible with Enter key;
> * Add padding at this input
>   ![image](https://user-images.githubusercontent.com/75343999/273672989-8836571a-ad5e-4349-895b-eb105f5649fc.png)
> 
> Assign to me please!!

okay you can work on this.i am assigning to you.
It will be great if you handle more similar issues in the same PR
