### ISSUE TITLE
Add callToACtion for comment in post on homepage

### ISSUE THREAD

**Issue by Tech-Shreyansh** [ConnectPlus-Org/ConnectPlus-Frontend#37]

**Comment by Advaith-RN** [comment]
Mind if i work on this?

**Comment by tarupathak** [comment]
Please assign me this issue.

**Comment by Tech-Shreyansh** [comment]
> Mind if i work on this?

No, I have assigned you. Please Go ahead.

**Comment by Tech-Shreyansh** [comment]
> Please assign me this issue.

I have assigned you. Please Go ahead.
