### ISSUE TITLE
CSS Modification Request: Center Alignment Issue in Loader for Loading Time

### ISSUE THREAD

**Issue by Rishabh2503** [ConnectPlus-Org/ConnectPlus-Frontend#48]
Before -
![image](https://github.com/ConnectPlus-Org/ConnectPlus-Frontend/assets/104566113/a142ca9e-7d9c-4706-ba6d-59a2a3179123)
After - 
Loader will be in Centre of screen for all devices

**Comment by Rishabh2503** [comment]
Please Assign me this modification ...

**Comment by Tech-Shreyansh** [comment]
> Please Assign me this modification ...

this has been fixed already work on other issues

**Comment by Tech-Shreyansh** [comment]
Thank You
